Домашнее задание:

● Создайте случайную матрицу А1 размерностью 5 на 5

● Транспонируйте матрицу A1

● Найдите обратную матрицу для А1

● Создайте диагональную матрицу - поэлементно перемножив единичную матрицу I и случайную матрицу A2 размерности 4 на 4

● Создайте нулевую матрицу размерности 3 на 3

● Для всех полученных матриц найдите: определитель, ранг и собственные значения

● Проанализируйте результаты

In [1]:
import numpy as np

In [7]:
A1 = np.random.random((5, 5))
A1

array([[0.35538564, 0.28688919, 0.05934876, 0.25136323, 0.23569517],
       [0.25831663, 0.18560213, 0.96637782, 0.84319107, 0.19260623],
       [0.35432412, 0.9812762 , 0.30404618, 0.19114427, 0.37658946],
       [0.30766199, 0.01207745, 0.43663345, 0.93551661, 0.47622607],
       [0.1069983 , 0.36527618, 0.75671844, 0.12501368, 0.45837879]])

In [8]:
np.transpose(A1)

array([[0.35538564, 0.25831663, 0.35432412, 0.30766199, 0.1069983 ],
       [0.28688919, 0.18560213, 0.9812762 , 0.01207745, 0.36527618],
       [0.05934876, 0.96637782, 0.30404618, 0.43663345, 0.75671844],
       [0.25136323, 0.84319107, 0.19114427, 0.93551661, 0.12501368],
       [0.23569517, 0.19260623, 0.37658946, 0.47622607, 0.45837879]])

In [9]:
np.linalg.inv(A1)

array([[ 5.72440151,  0.8871291 , -1.94577336, -1.98634932,  0.34606463],
       [-1.72410734,  0.07131849,  1.78777534,  0.13412431, -0.75156936],
       [ 0.56447399,  0.9620082 , -0.6678651 , -1.0018947 ,  0.895126  ],
       [-1.93759309,  0.2335467 ,  1.00014833,  1.35220269, -1.32837889],
       [-0.3657415 , -1.91574776, -0.14067771,  1.64198687,  1.5842994 ]])

In [23]:
A2 = np.random.random((4, 4))
I = np.eye(4)

In [43]:
A3 = I * A2
A3

array([[0.43050202, 0.        , 0.        , 0.        ],
       [0.        , 0.52447816, 0.        , 0.        ],
       [0.        , 0.        , 0.40718253, 0.        ],
       [0.        , 0.        , 0.        , 0.68519322]])

In [30]:
A4 = np.zeros([3, 3])
A4

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Вычисление определителя для полученных матриц:

In [48]:
np.linalg.det(A1)

-0.05322315104309332

In [44]:
np.linalg.det(A3)

0.06299481291951547

In [42]:
np.linalg.det(A4)

0.0

Вычисление ранга для полученных матриц:

In [31]:
np.linalg.matrix_rank(A1)

5

In [45]:
np.linalg.matrix_rank(A3)

4

In [33]:
np.linalg.matrix_rank(A4)

0

Вычисление собственных значений для полученных матриц:

In [36]:
np.linalg.eig(A1)

(array([ 2.03265723+0.j        , -0.67174155+0.j        ,
         0.16578806+0.j        ,  0.35611281+0.32908816j,
         0.35611281-0.32908816j]),
 array([[ 0.23961407+0.j        , -0.23209896+0.j        ,
          0.90244163+0.j        , -0.13305254-0.03810294j,
         -0.13305254+0.03810294j],
        [ 0.54957768+0.j        ,  0.63135351+0.j        ,
         -0.23185381+0.j        , -0.25364646+0.14537273j,
         -0.25364646-0.14537273j],
        [ 0.50358107+0.j        , -0.67835177+0.j        ,
          0.07982543+0.j        ,  0.10321129+0.31022174j,
          0.10321129-0.31022174j],
        [ 0.4568914 +0.j        ,  0.14819431+0.j        ,
         -0.3391871 +0.j        , -0.34665278-0.41346883j,
         -0.34665278+0.41346883j],
        [ 0.42214432+0.j        ,  0.25573451+0.j        ,
         -0.10209277+0.j        ,  0.70523805+0.j        ,
          0.70523805-0.j        ]]))

In [46]:
np.linalg.eig(A3)

(array([0.43050202, 0.52447816, 0.40718253, 0.68519322]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]))

In [38]:
np.linalg.eig(A4)

(array([0., 0., 0.]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))